### ISSUE TITLE
Android 12 tracking issue

### ISSUE THREAD

**Issue by danielfullmer** [danielfullmer/robotnix#126]
Things we would like to have working/tested before we can change the default `androidVersion`.

- [x] Generic device support (https://github.com/danielfullmer/robotnix/pull/127)
- [x] Pixel vendor code (https://github.com/danielfullmer/robotnix/pull/128)
- [x] Vanilla flavor (https://github.com/danielfullmer/robotnix/commit/40f30cab5f2fa11784b23ce3725564cf668877fc)
- [ ] Vanilla kernel building
- [x] GrapheneOS flavor (https://github.com/danielfullmer/robotnix/commit/bb7d6680fd686d2df4792bb654f6921fdbde9e8e)
- [x] Signed builds (https://github.com/danielfullmer/robotnix/commit/375505c18e92d4ec5f83b1665137d2afe162936f and https://github.com/danielfullmer/robotnix/commit/fdfc054af9247f8620cd838ca0e5886368f07141)
- [x] Browsers/webview
- [x] MicroG (0570e4e7eebe667caf28b6a081def708230c504a)
- [x] F-Droid 
- [x] OTA Updates (5465d8110b5fc0c7bea4109921e2d5d2e9947db3)
- [x] Seedvault (1de0a7f41227e56b6c13ffd8257f46febdaa8ac9)
- [ ] Emulator and/or cuttlefish
- [ ] Cleanup APV configs
